"""Public api-service schema exports.

Phase 4 schemas land incrementally:
- 04-01: auth + common
- 04-02: keys + billing
- 04-03 (final): model_catalog (read-only subset; admin writes in Phase 5)
"""

from api_service.schemas.auth import (
    ChangePasswordRequest,
    ChangePasswordResponse,
    LoginRequest,
    LoginResponse,
    LoginResponseData,
    LoginWithCodeRequest,
    LogoutResponse,
    RefreshResponse,
    RefreshResponseData,
    RefreshTokenResponse,
    RefreshTokenResponseData,
    RegisterRequest,
    RegisterResponse,
    RegisterResponseData,
    ResetPasswordRequest,
    SendEmailCodeRequest,
    UserData,
    UserInfoResponse,
    UserInfoResponseData,
    VerifyEmailRequest,
)
from api_service.schemas.billing import (
    ApiCallLogItem,
    BalanceResponseData,
    BalanceTransactionItem,
    TopupOrderItem,
    UsageAnalyticsBucket,
    UsageAnalyticsBucketCost,
    UsageAnalyticsData,
    UsageAnalyticsModel,
    UsageAnalyticsOverview,
    UsageAnalyticsRange,
    UsageStatItem,
    VoucherRedeemRequest,
    VoucherRedeemResponseData,
    VoucherRedemptionItem,
)
from api_service.schemas.common import (
    ApiResponse,
    AuthBaseResponse,
    AuthErrorResponse,
    DateTimeModel,
)
from api_service.schemas.keys import (
    ApiKeyCreateData,
    ApiKeyCreateRequest,
    ApiKeyItem,
    ApiKeyUpdateRequest,
)
from api_service.schemas.model_catalog import (
    ModelCategoryBrief,
    ModelCategoryItem,
    ModelVendorBrief,
    ModelVendorItem,
    SupportedModelDetail,
    SupportedModelItem,
)

__all__ = [
    "ApiCallLogItem",
    "ApiKeyCreateData",
    "ApiKeyCreateRequest",
    "ApiKeyItem",
    "ApiKeyUpdateRequest",
    "ApiResponse",
    "AuthBaseResponse",
    "AuthErrorResponse",
    "BalanceResponseData",
    "BalanceTransactionItem",
    "ChangePasswordRequest",
    "ChangePasswordResponse",
    "DateTimeModel",
    "LoginRequest",
    "LoginResponse",
    "LoginResponseData",
    "LoginWithCodeRequest",
    "LogoutResponse",
    "ModelCategoryBrief",
    "ModelCategoryItem",
    "ModelVendorBrief",
    "ModelVendorItem",
    "RefreshResponse",
    "RefreshResponseData",
    "RefreshTokenResponse",
    "RefreshTokenResponseData",
    "RegisterRequest",
    "RegisterResponse",
    "RegisterResponseData",
    "ResetPasswordRequest",
    "SendEmailCodeRequest",
    "SupportedModelDetail",
    "SupportedModelItem",
    "TopupOrderItem",
    "UsageAnalyticsBucket",
    "UsageAnalyticsBucketCost",
    "UsageAnalyticsData",
    "UsageAnalyticsModel",
    "UsageAnalyticsOverview",
    "UsageAnalyticsRange",
    "UsageStatItem",
    "UserData",
    "UserInfoResponse",
    "UserInfoResponseData",
    "VerifyEmailRequest",
    "VoucherRedeemRequest",
    "VoucherRedeemResponseData",
    "VoucherRedemptionItem",
]
