-- init_tables.sql — aggregated schema initializer.
--
-- Execute against a pre-created set of databases (one per service). Each
-- SOURCE directive pulls the service-owned schema snapshot from
-- scripts/sql/<service>_schema.sql. Snapshots are regenerated by
-- `mysqldump` and are NOT the source of truth; Alembic revisions under
-- migrations/<service>/versions are. See migrations/README.md for the
-- authoritative workflow.
--
-- Dependency order:
--   admin -> user -> testing
-- router-service is intentionally omitted — it has no database in the
-- current design; all routing metadata lives in user-service tables.

SOURCE scripts/sql/admin_schema.sql;
SOURCE scripts/sql/user_schema.sql;
SOURCE scripts/sql/testing_schema.sql;
